### ISSUE TITLE
UPDATE: Remove snippet details for making billing address required for paypal standard

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#132]
ISSUE CONTENT
**URL:** https://givewp.com/top-5-give-snippets-improve-donation-form/

**PROBLEM:**  Now that we have the option to enable and disable billing address for paypal standard.  Snippet for making billing address required does not apply anymore. Also this the github url links to 404

**SOLUTION:** Make necessary changes

**Comment by marutim** [comment]
@mathetos I do not have access to edit this article and from the comments above it seems @Benunc  has neither. So assigning it to you.

**Comment by mathetos** [comment]
The article has been updated with LOTS of updates, the whole article is almost totally absolete now. We need a new one!
