### ISSUE TITLE
UPDATE: Snippet in the doc to be compatible with Give 2.0+

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#135]
ISSUE CONTENT
**URL:** https://givewp.com/documentation/developers/how-to-query-donor-information/

**PROBLEM:** Update the doc, esp the snippet to be compatible with Give 2.0+

**Comment by Benunc** [comment]
I re-did this doc today, and published. It's not as full-featured now, but it at least is up to date with GIve 2.0+
