### ISSUE TITLE
UPDATE: Email Report Settings Have Changed

### ISSUE THREAD

**Issue by michelleames** [impress-org/give-docs#148]
**URL:** https://givewp.com/documentation/add-ons/email-reports/

**PROBLEM:** The settings screen is located in your WP-Admin under Donations > Settings > Emails > Email Reports. (This is no longer accurate.)

**SOLUTION:** 

The settings screen is located in your WP-Admin under Donations > Settings > Emails. 

Located the "Daily Email Report," "Weekly Email Report," or "Monthly Email Report" in the emails list and click the gear icon to enable/disable and edit the email report.

**_(There is more to edit on this doc...if you'd like me to take a crack at it, please let me know.)_**

![screen shot 2018-03-05 at 8 41 52 am](https://user-images.githubusercontent.com/14227933/36978211-b746c284-2051-11e8-876c-6f82d1c8b86d.png)
![screen shot 2018-03-05 at 8 43 56 am](https://user-images.githubusercontent.com/14227933/36978212-b7602526-2051-11e8-982f-f8a53980c436.png)

**Comment by mathetos** [comment]
I believe we already have an issue on this @michelleames that @benunc is addressing this morning

**Comment by Benunc** [comment]
This is add-on doc related, and It's not on an issue currently.

**Comment by mathetos** [comment]
Thanks @Benunc I read too quickly.

@michelleames I updated the doc. If you want to review it and make additional tweaks I'm all for it. Just update us here and close out the issue once you're done. Thanks!

**Comment by mathetos** [comment]
Closing for now.

**Comment by marutim** [comment]
Updates have not been made to this doc here: https://givewp.com/documentation/add-ons/email-reports/
Update the screenshot to display the latest settings
Reopening it

**Comment by kevinwhoffman** [comment]
Moving this to the Docs pipeline as I think it got lost in New Issues.

**Comment by marutim** [comment]
@mathetos I have worked on the documentation to update the screenshots and settings details.

I was not able to complete the settings details as Succuri started to deny access. I was doing nothing different than I was doing so far.

![image](https://user-images.githubusercontent.com/3498917/51388458-7a50e900-1b4f-11e9-940a-212f44debffb.png)

**Comment by marutim** [comment]
@mathetos I have made the changes and published it here: https://givewp.com/documentation/add-ons/email-reports/

Can you please review and suggest changes, if any.
