### ISSUE TITLE
web-doc(devs): update custom fields docs

### ISSUE THREAD

**Issue by Benunc** [impress-org/give-docs#166]
**User Story** 
From Scott:
> If you change the add_post_meta call to give_update_payment_meta in the github snippet at:
> https://github.com/WordImpress/Give-Snippet-Library/blob/master/form-customizations/custom-fields-plugin.php
> 
> and change the field from the custom engraving example to a referral source example (to minimize the need to re-write the article's other content to maybe just the validation part), you have a working example that can be decomposed to use to replace the examples in these articles (or merge the articles into one article):
> 
> https://givewp.com/documentation/developers/how-to-create-custom-form-fields/
> https://givewp.com/documentation/developers/how-to-add-custom-email-tags/

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/documentation/developers/how-to-create-custom-form-fields/|*required*|

## Related Give Core/Add-on issues
https://github.com/WordImpress/Give-Snippet-Library/issues/73

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] The doc uses the updated snippet from the snippet library
- [ ] The doc is combined into one doc (custom fields and email tags) *up for discussion*
- [ ] Developers understand the `give_update_payment_meta` function is the new standard

**Comment by mathetos** [comment]
@Benunc can you review this issue again? Is it still a pain point or has this now been addressed adequately? Please review, and update the OP, or close. Thanks!

**Comment by Benunc** [comment]
it's been updated. closing.
