### ISSUE TITLE
web-doc: Update the current supported gateways details for recurring

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#168]
**User Story** 
Update the current supported gateways details for recurring donations here https://givewp.com/addons/recurring-donations/

It says that Stripe + Plaid ACH does not support recurring yet, whereas the latest release supports it

## Assets
![image](https://user-images.githubusercontent.com/3498917/40052977-3a94ed1c-585d-11e8-91ad-4c52409c2d52.png)

## Acceptance Criteria
We just need to edit that detail.

**Comment by mehul0810** [comment]
More details for Stripe add-on,
✅ Stripe CC - supports recurring
✅ Stripe + Plaid - supports recurring
❌ iDEAL - not yet support recurring

**Comment by mathetos** [comment]
I believe this is resolved.
