### ISSUE TITLE
web-doc(updates): create how to update Give core and add-ons doc.

### ISSUE THREAD

**Issue by Benunc** [impress-org/give-docs#173]
**User Story** 
Describe what the user wants in regard to this doc in these terms:
As a `Give-admin`, I want `clear instructions on updating Give and add-ons` so that `my site updates work correctly`.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Doc Title:**|How To Update Give|*required* if its a new doc|
|**New Url:**|https://givewp.com/documentation/resources/how-to-update-give|*required*|
|**Google Docs URL**| none yet |*required* if creating a new doc

## Assets
None Yet

## Acceptance Criteria
List what will make this doc ready to publish. Example:

**This doc is ready to publish when:**
- [ ] I know how to update Give with no active add-ons
- [ ] I know how to activate Give with multiple add-ons. 
- [ ] I understand the importance of updating Core before add-ons.

**Comment by mathetos** [comment]
@Benunc Do you still see a need for this doc? The issue above isn't super clear on why this is a felt need for customers. Please expound the OP above or close this out if you think it's no longer a need.
