### ISSUE TITLE
web-doc(gateway): create doc for Stripe + Plaid ACH setup

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give-docs#176]
## Necessary Items
**User Story** 
As a site admin, I want to know how to set up Stripe + Plaid ACH so that I can accept ACH payments.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Doc Title:**|Setting up Stripe + Plaid ACH|
|**New Url:**|https://givewp.com/documentation/add-ons/stripe-gateway/plaid-setup|
|**Google Docs URL**|https://docs.google.com/document/d/1dH1nT_T2T6Wx8C7tq2BeKOb7zG5HH7HFgcdDuhaziW8/edit

## Assets
Setting up an account:
https://plaid.com/docs/link/stripe/

Stripe ACH guide:
https://stripe.com/docs/ach

## Acceptance Criteria
List what will make this doc ready to publish. Example:

**This doc is ready to publish when:**
- [x] I understand that Stripe and Plaid are different from each other.
- [x] I understand that Plaid is free only for the first 100 accounts, and pricing for unlimited.
- [x] I understand how to link Plaid to Stripe, and setup Plaid in Give.
- [x] I understand the difference between Test, Development, and Production API modes. 
- [x] I understand how to make test payments.

**Comment by mathetos** [comment]
This was addressed via this doc:
https://givewp.com/documentation/add-ons/stripe-gateway/stripe-plaid/
