### ISSUE TITLE
web-doc(gift-aid): show users {meta_donation__give_gift_aid_accept_term_condition} will display whether donor selected gift aid

### ISSUE THREAD

**Issue by samsmith89** [impress-org/give-docs#179]
## Necessary Items
**User Story**
As a site admin, I want to know how to pass information from about whether the donor opted-in to Gift Aid in the New Donation admin email so that we can manage those donations from emails.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/documentation/add-ons/gift-aid/general-settings/|*required*|
|**Google Docs URL**|https://docs.google.com/document/d/1dH1nT_T2T6Wx8C7tq2BeKOb7zG5HH7HFgcdDuhaziW8/edit

## Assets
![screen shot 2018-06-26 at 10 10 21 am](https://user-images.githubusercontent.com/20672471/41937060-3dd660e8-795d-11e8-8c33-015a7457edc1.png)

This passes "ON" if the donor opted-in, and it is empty if they didn't:
![screen shot 2018-06-26 at 10 11 35 am](https://user-images.githubusercontent.com/20672471/41937063-4103b69e-795d-11e8-8f42-43a03e283dfa.png)

## Acceptance Criteria
List what will make this doc ready to publish. Example:

**This doc is ready to publish when:**
- [ ] I see an updated screenshot of the use of this template tag.
- [ ] I understand how to use this template tag.
- [ ] I understand what information is passed with this template tag.

**Comment by samsmith89** [comment]
**Here is the content that will be added to the page:**

Now let’s say you want to let your team know whether or not a donor opted-in to Gift Aid. This can be accomplished by marking whether this took place in the <a>New Donation</a> email that is sent to the listed email addresses when a donation is made.

The template tag that we will use is {meta_donation__give_gift_aid_accept_term_condition}

This will either pass in “on” when a donor selects the checkbox, or will pass nothing if the donor does doesn’t opt-in.

Here is a visual example:

![41937060-3dd660e8-795d-11e8-8c33-015a7457edc1](https://user-images.githubusercontent.com/20672471/42220302-88eb78e0-7e9c-11e8-9a3b-6bf8f4a2f97b.png)

You can see how we set aside the space with “Gift Aid:” so we know where the value would display if it is present.

Here is the email that is generated when a donor select Gift Aid:

![41937063-4103b69e-795d-11e8-8f42-43a03e283dfa](https://user-images.githubusercontent.com/20672471/42220311-908b28fc-7e9c-11e8-8b1f-f906348eff97.png)

Here you can see the “on” is displaying in the “Gift Aid:” area that we defined when setting up the email. If the donor didn’t opt-in to Gift Aid this area would be blank.

**Comment by Benunc** [comment]
add the edits discussed in Slack and ping me again, and I'll take a look.

**Comment by samsmith89** [comment]
Published live at https://givewp.com/documentation/add-ons/gift-aid/general-settings/

**Comment by mathetos** [comment]
Great work, @samsmith89 Thanks!
