### ISSUE TITLE
web-doc: update info about the unavailability of 3D secure cards

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#182]
## Necessary Items
**User Story** 
Update the doc to include the info about the unavailability of 3D secure cards for stripe checkout.

Since the fixing of the bug https://github.com/WordImpress/Give-Stripe/issues/266, Mehul informed me that fix was to revert back to token for stripe checkout which means it will not support Stripe 3D cards.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/documentation/add-ons/stripe-gateway/|*required*|

## Assets
Provide screenshots and/or videos that already exist here if relevant

## Related Give Core/Add-on issues
https://github.com/WordImpress/Give-Stripe/issues/266

**Comment by mehul0810** [comment]
3D secure payments will not work for Stripe Checkout as per the screenshot below:
![image](https://user-images.githubusercontent.com/1852711/42332388-72ed6eea-8095-11e8-99b8-79b2cbf0e670.png)

However, Stripe CC fields will support 3D secure payments same as earlier. There is an open issue https://github.com/WordImpress/Give-Recurring-Donations/issues/678 related to 3D secure payment with Stripe CC and recurring. So, it will get fixed as a part of release by next week.

**Comment by samsmith89** [comment]
Here is the content for the page. The text will be placed here:

![screen_shot_2018-10-19_at_4_44_08_pm](https://user-images.githubusercontent.com/20672471/47242900-43d3c880-d3be-11e8-9145-67fe44ab6d5c.png)

`First, remove all mentions of Bitcoin support on the page.`

`<p><strong>Note:</strong> 3D secure card payments are not available when using the Stripe Modal Window. If accepting 3D secure card payments are necessary, using the standard Stripe credit card fields is required.</p>`

I reviewed this document for further knowledge on 3D secure card payments:
https://stripe.com/docs/sources/three-d-secure

This echoes what is stated in the issue that stripe.js must be activated client side to work.

**Comment by mathetos** [comment]
Looks great @samsmith89 Please login to the site on Monday and make those updates to the doc accordingly and publish. Thanks!

**Comment by samsmith89** [comment]
- Removed references to Alipay and Bitcoin
- Changed the Modal window screenshot (had Alipay in it)
- Added the attached text under the screenshot. 
Closing
