### ISSUE TITLE
web-doc: update recurring with the latest functionality and screenshots.

### ISSUE THREAD

**Issue by Benunc** [impress-org/give-docs#186]
**User Story** 
As a `site admin`, I want `to know all of the functionality of Give's most popular add-on` so that `I can fully utilize it and educate donors`.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Doc Title:**|Provide the title if it's a new doc|*required* if its a new doc|
|**Current Url:**|https://givewp.com/documentation/add-ons/recurring-donations/managing-subscriptions/ (will stay) |*required*|
|**New Url:**|https://givewp.com/documentation/add-ons/recurring-donations/managing-subscriptions/updating-payment-info (not there yet) |*required*|
|**Google Docs URL**|None yet|*required* if creating a new doc

### Main Doc
**This doc is ready to publish when:**
- [x] I understand all that a donor can do from the main shortcode output.
- [x] I link to the PCI compliance doc for clarification on where payment info is stored
- [x] I understand where the page is set up, and how to change it.
- [x] I see a screenshot of the Subscription page shortcode output.

### New Doc
**This doc is ready to publish when:**
- [x] I see a screenshot of the update payment info section.
- [x] I understand that clicking the link sends an API call to the gateway
- [x] I understand that the card info is not stored on the site.
- [x] I link to the PCI compliance doc

**Comment by Benunc** [comment]
Main doc updated. seeking feedback on the plan for the new doc @mathetos

**Comment by mathetos** [comment]
@Benunc I like the list you have above on when the New Doc is ready. I think the only thing to add additionally is a list of the Gateways that support Recurring AND this feature, which I believe is only Stripe right now... but that's a really important detail to make explicit, and I think we need confirmation from Devteam about which Gateways support that.

**Comment by Benunc** [comment]
Published. https://givewp.com/documentation/add-ons/recurring-donations/managing-subscriptions/updating-payment-information/
