### ISSUE TITLE
doc: update recurring info on Mollie Gateway page

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#192]
**User Story** 
As a user, I find the information in the Mollie gateway addon page https://givewp.com/addons/mollie-payment-gateway/  incorrect. Here it says, mollie support **Yearly** subscriptions which is incorrect.

GH link about this issue: https://github.com/impress-org/give-mollie/issues/7

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Current Url:**|https://givewp.com/addons/mollie-payment-gateway/|*required*|

## Assets
![image](https://user-images.githubusercontent.com/3498917/46412483-4edef580-c73c-11e8-9195-bb566d7c6181.png)

## Related Give Core/Add-on issues
https://github.com/impress-org/give-mollie/issues/7

**Comment by mathetos** [comment]
Good catch @marutim -- Fixed!
