### ISSUE TITLE
doc: add new doc for Stripe about common credit card error messages

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#193]
## Necessary Items
**User Story** 
As a Give Admin, I want to understand why a credit card error message is shown to my donors for any reason. Give's messages don't explain fully what happened at the payment gateway, so a doc that would show the Give message and the corresponding Stripe message would be best.

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Doc Title:**|Common Credit Card Error Messages|*required* |
|**Current Url:**|https://givewp.com/documentation/add-ons/stripe-gateway/common-error-messages|*required*|
|**Google Docs URL**|TBD|*required*

## Assets Needed
Just one screenshot of one of the common Stripe error messages would be sufficient for this doc.

## Acceptance Criteria
List what will make this doc ready to publish. Example:

**This doc is ready to publish when:**
- [x] I see a list of Give-Stripe error messages based on [this code here](https://github.com/impress-org/give-stripe/blob/release/2.1.2/includes/class-give-stripe-logger.php#L93-L138) and that each explains WHY that message appears for a donor, including any potential troubleshooting tips to resolve that if that message is appearing for EVERY donation.
- [x] Each of the Give error messages in that code above, corresponds to its proper Stripe error code listed here: https://stripe.com/docs/error-codes
- [ ] There's at least one screenshot of a common Give-Stripe error message within a Give Form

**Comment by mathetos** [comment]
We don't have a tag for "not a high priority" so just saying that here for now.

**Comment by Benunc** [comment]
Very close to finishing this, but I am now second-guessing my approach. I went through the list of error messages and provided context, but then when I attempt to get the error code for a screenshot, it seems to be pulling the text directly from Stripe:

For example: The error message string in give-stripe is `The card was declined.` yet this is the error I get:

![screen shot 2019-02-13 at 9 14 39 am](https://user-images.githubusercontent.com/9629102/52717815-f7655780-2f6f-11e9-965a-ed22bb025cd3.png)

I made my post a draft while we determine what's up. https://givewp.com/wp-admin/post.php?post=341574&action=edit

**Comment by Benunc** [comment]
After reviewing this, I think that the problem is my ability to replicate the error for a screenshot, not so much the error messages themselves. I frequently run into errors on customer sites that are like these. (in the logs.)

I am going to remove the confusing screenshot and publish this.
