### ISSUE TITLE
web-doc: add "contact information" sub-page to email settings

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#194]
I'll fill out the whole issue better later, but here's what's currently missing from the site:
![image](https://user-images.githubusercontent.com/930724/47064673-469fa500-d195-11e8-946d-65e26cd83dfa.png)

## Necessary Items
**User Story** 
Describe what the user wants in regard to this doc in these terms:
As a ________, I want ________ so that ________.

**Doc Details**

|**ITEM**|**DESCRIPTION**|**REQUIRED**|
|---|---|---|
|**Doc Title:**|Provide the title if it's a new doc|*required* if its a new doc|
|**Current Url:**|Provide the URL where the change will be made or where the new doc will be published|*required*|
|**New Url:**|The new URL location|*required* if organizing to a new location|
|**Google Docs URL**|Provide a URL to your Google Docs draft|*required* if creating a new doc

## Assets
Provide screenshots and/or videos that already exist here if relevant

## Related Give Core/Add-on issues
List any existing Give Core or Add-on issues that provide context or necessary info for this doc

## Acceptance Criteria
List what will make this doc ready to publish. Example:

**This doc is ready to publish when:**
- [ ] I see an updated screenshot of the new `Enabled Gateways` UI in Give 2.1.
- [ ] I understand how to customize gateway labels in the new Give 2.1 UI.
- [ ] I understand how to enable/disable gateways in the new Give 2.1 UI.
- [ ] I understand the meaning of `Default Gateway` in the new Give 2.1 UI.

**Comment by marutim** [comment]
@mathetos Added the doc here: https://givewp.com/documentation/core/settings/emails/contact-information/
Please review and close the issue.

**Comment by mathetos** [comment]
Good work on this one @marutim !
