### ISSUE TITLE
web-doc: create a new doc to include Donor note email for Give 2.3

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#196]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/settings/emails/donor-note
* Doc Title: Donor Note
* Issue Type: New

## Issue Description
Create a new doc to include details about the new "Donor note" email. The template for this email can be edited in Donations > Settings > Emails > Donor Note

## Related Give Core/Add-on issues
Give Core issue for this new feature: https://github.com/impress-org/give/issues/2159
Web doc issue link for updating the donation details: https://github.com/impress-org/give-docs/issues/195

## Acceptance Criteria
**This doc is ready to publish when:**
- [ ] I understand how to edit/update the Donor note email template

**Comment by samsmith89** [comment]
Just published at https://givewp.com/documentation/core/settings/emails/donor-note/
@mathetos
