### ISSUE TITLE
web-doc: update screenshot and copy to show the donor note on give_receipt table

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#197]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/shortcodes/give_receipt/
* Issue Type: Update

## Issue Description

Update the screenshot on this page that shows the full Donation receipt, and make sure it's showing the "Donation Note" section that should be reflected when a "Donor note" has been added to an individual donation.

Also add copy specifically about that feature, and link to [this page](https://givewp.com/documentation/core/donations/donation-details/) that explains the full donation note feature. 

## Assets

This is the image that needs to be updated:
![image](https://user-images.githubusercontent.com/930724/47472177-85031880-d7c2-11e8-97a5-fe6d2e460e16.png)

## Related Give Core/Add-on issues

* [Epic issue](https://github.com/impress-org/give-docs/issues/188)

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] I see the updated doc
- [ ] There is new text about that feature of the donation receipt table
- [ ] There is a link to the donation details doc

**Comment by samsmith89** [comment]
@mathetos I just confirmed that the donor note doesn't display in the receipt on the donation history page after it has been created:

![give local_donation-history__payment_key 969476873e72ad1c68d06496c1404b23](https://user-images.githubusercontent.com/20672471/47566785-bd0d7700-d8fa-11e8-9f3d-ecb972d28b6d.png)

Is there something I'm missing here?

**Comment by mathetos** [comment]
Thanks @samsmith89 I misunderstood the original developer video on this part of the donor note feature. That's my mistake. This is closed for now, thanks!
