### ISSUE TITLE
web-doc: add new export donations doc

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#198]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/tools/exports-tab/export-donations
* Doc Title: Export Donations
* Issue Type: New

## Issue Description

The new export donations tool is very full-featured and needs a more complete description than it has currently. 

This is the current page:
https://givewp.com/documentation/core/tools/exports-tab/

The "Export Donations" section should be changed to the following:
> This exports a CSV (Comma Separated Values) file of all your donations over any given period of time that you designate.
> 
> This export lists every single donation that you received during the period that you designated. See [this documentation article] for full details.

And that link would link to the new sub-page article.

## Assets

It should have at least one screenshot of the full page settings.

It should also have a sample download CSV like it currently does, but with full donor comments and whatnot.

## Related Give Core/Add-on issues

New features like exporting donor comments should be described in detail.
* https://github.com/impress-org/give/issues/3743

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] A new sub-page doc exists here: https://givewp.com/documentation/core/tools/exports-tab/export-donations
- [ ] That doc is listed correctly as "Articles in the Section" on this page: https://givewp.com/documentation/core/tools/exports-tab/
- [ ] The new doc has at least one screenshot
- [ ] The new doc has at least one CSV file as a sample to download.

**Comment by samsmith89** [comment]
Here is the link to the Google doc for progress:
https://docs.google.com/document/d/19VPy_b0RUTofqiASo8RmcJ6rMgF-UYJzYPwHqm1Rs5E/edit?usp=sharing

**Comment by samsmith89** [comment]
Published at https://givewp.com/documentation/core/tools/exports-tab/export-donations/ and ready to close.

I also updated the https://givewp.com/documentation/core/tools/exports-tab/ parent page to reflect the changes in this doc.

**Comment by mathetos** [comment]
Well done, thanks @samsmith89 !
