### ISSUE TITLE
web-doc: update general settings with live currency preview

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#199]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/settings/general-settings/currency-settings/
* Issue Type: Update

## Issue Description

Give has a live currency preview feature now which should be documented with a description and a GIF.

## Assets

An animated GIF should be made to show the preview working as intended.

## Related Give Core/Add-on issues

* https://github.com/impress-org/give/issues/3490

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] I see "Currency Preview" added as a section to the above existing doc
- [x] I see an animated GIF highlighting how the preview works correctly.

**Comment by marutim** [comment]
@mathetos I have made the above changes. Please review. Thanks

**Comment by mathetos** [comment]
Looks good, the only small change was I put the image preview BELOW the setting description. Thanks!
