### ISSUE TITLE
web-doc: update Form Display to reflect all current options

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#200]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/give-forms/form-display/
* Issue Type: Update

## Issue Description

This doc is outdated. It needs to have the following Form Display options added with detail:

* Default Gateway
* Name Title Prefix
* Company Donations
* Anonymous Donations
* Donor Comments

## Related Give Core/Add-on issues

* Same goes for the General Settings "Display Options" tab -- making an issue for that soon.

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] The above bulleted sections have been added with relevant links to related docs
- [x] The order of the sections mimics the plugin settings

**Comment by marutim** [comment]
Doc Created: https://docs.google.com/document/d/1p_2KCEqPXcYmulooUAlHvCx_L53d-e9QLzqgJIyrhQM/edit#

Also, we need to update the Global Display options settings page here https://givewp.com/documentation/core/settings/display-options/

**Comment by mathetos** [comment]
@marutim You can easily use a lot of the new wording that Sam created for the Global display options screen that are already reflected on this page here:
https://givewp.com/documentation/core/settings/display-options/

That should help get this done quicker. Thanks!

**Comment by marutim** [comment]
Updated the doc with current options here: https://givewp.com/documentation/core/give-forms/form-display/

@mathetos can you review this and let me know if you want to make any changes?

Thanks

**Comment by mathetos** [comment]
Great work on this one @marutim Thanks!
