### ISSUE TITLE
web-doc: update Settings > Display Options with new settings available in Core

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#201]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/settings/display-options/
* Issue Type: Update

## Issue Description

This doc is outdated and needs the following new settings added:
* Name Title Prefix
* Company Donations
* Anonymous Donations
* Donor Comments

This doc should also link to [this page](https://givewp.com/documentation/core/give-forms/form-display/) to indicate how these settings can be overwritten per form.

## Related Give Core/Add-on issues

* #200 

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] The above sections are added
- [ ] The sections are shown in the order that reflects the plugin order.

**Comment by samsmith89** [comment]
Here is a link to the google doc:
https://docs.google.com/document/d/1z1F0G9S28HIFA0ClYhN4gDH-A7aFbYCuni7ywzzq8_o/edit?usp=sharing

**Comment by samsmith89** [comment]
This is published at https://givewp.com/documentation/core/settings/display-options/ Let me know if there is anything that needs to be changed.

**Comment by mathetos** [comment]
Looks great, Sam. Love the screenshots.
