### ISSUE TITLE
web-doc: create a doc to explain the detailed recurring settings to avoid confusion

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give-docs#202]
## Issue Info
* Docs URL: https://givewp.com/documentation/configure-recurring-settings
* Doc Title: Understanding the Recurring Add-ons settings.
* Issue Type: New

## Issue Description
Recently, We have noticed that lots of customers have reported a similar issue related to Admin Defined recurring settings where we think to add a detailed document to explain these settings including Donor Choice, Preset Period, Admin Defined, and Custom Amount with Recurring. This will help our team as well as customers to avoid confusion regarding the recurring functionality.

## Assets
**Check this video:** https://www.useloom.com/share/d98ec4ffcb07417881547b929339e25d

There are other scenario's as well. Let me know if you have any query regarding the functionality.

## Related Give Core/Add-on issues
- https://github.com/impress-org/give-recurring-donations/issues/795
- https://github.com/impress-org/give-recurring-donations/issues/291

## Acceptance Criteria
**This doc is ready to publish when:**
- [x] I see a detailed document explaining all the recurring add-on functionality.
- [x] I understand what is best settings to use on my site.
- [x] I understand how to enable one time or recurring for a custom amount.

**Comment by Benunc** [comment]
I added a new section to https://givewp.com/documentation/add-ons/recurring-donations/recurring-donation-forms/ under the Admin Defined example section. THis is done.
