### ISSUE TITLE
web-doc: update the existing payumoney documentation

### ISSUE THREAD

**Issue by mehul0810** [impress-org/give-docs#203]
## Issue Info
* Docs URL: https://givewp.com/documentation/add-ons/payumoney/
* Issue Type: Update

## Issue Description
Earlier, there were 2 different domains for TEST and LIVE payments. However, now registering through payumoney.com will generate TEST and LIVE credentials.

**URL:** https://www.payumoney.com/

## Assets
Payment Screen
![image](https://user-images.githubusercontent.com/1852711/49730841-9c796080-fc9f-11e8-9b9f-ab2fc3fc4e18.png)

## Related Give Core/Add-on issues
https://github.com/impress-org/give-payumoney/issues/15

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] I see an updated screenshot of managing payment method label.
- [ ] I understand how to configure and process a test donation using PayUMoney.

**Comment by mehul0810** [comment]
We're now supporting PayUBiz account with our add-on. We've added a setting to handle that. Please refer PR for more details https://github.com/impress-org/give-payumoney/pull/17 which have detailed explanation and a testing video.

Let me know if you've any questions

**Comment by mathetos** [comment]
@marutim Can you start a Google Doc to update this, this week?

**Comment by marutim** [comment]
Link to the doc: https://docs.google.com/document/d/1t_xshTbHdMh95pLai-RV6w7QSiJtS00cI0a-XXyILqU

**Comment by marutim** [comment]
@mathetos Can you review the above doc and let me know if you have any comments.

**Comment by marutim** [comment]
@mathetos I have updated the doc https://givewp.com/documentation/add-ons/payumoney/
Please review. Thanks

**Comment by mathetos** [comment]
Looks great, thanks for that!
