### ISSUE TITLE
web-doc: add new give donor wall block doc

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#207]
## Issue Info
* Docs URL: https://givewp.com/documentation/core/blocks/give-donor-wall-block
* Doc Title: Give Donor Wall Block
* Issue Type: New

## Issue Description

We need a detailed overview of the new Give Donor Wall block. This will be a sub-page of the new "blocks" section addressed in issue #204 

## Assets

This will need screenshots for sure, as appropriate to describe the crucial features.

## Related Give Core/Add-on issues

* https://github.com/impress-org/give/issues/3813

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] #204 is resolved first
- [ ] The new page is created as a sub-page of the "blocks" section
- [ ] The page is called "Give Donor Wall Block"
- [ ] It describes each control of the block in detail
- [ ] It describes each setting in the sidebar in detail and how that affects the display/functionality of the block.

**Comment by samsmith89** [comment]
I assigned the wrong one to myself

**Comment by samsmith89** [comment]
Here is the google doc for the content:
https://docs.google.com/document/d/1x5yTqbJuAblH-btmG3e73RdXcUamhf1s8IqQSDe-kvc/edit

**Comment by samsmith89** [comment]
Published here https://givewp.com/documentation/core/blocks/donor-wall-block/

**Comment by samsmith89** [comment]
Sounds good. I’ll make that happen.

**Comment by samsmith89** [comment]
@mathetos Finished and published
