### ISSUE TITLE
web-doc: update Fee Recovery add-on page to add the latest screenshots

### ISSUE THREAD

**Issue by marutim** [impress-org/give-docs#208]
## Issue Info
* Docs URL: https://givewp.com/addons/fee-recovery/
* Issue Type: Update the screenshots in this page.

## Issue Description
The screenshot for the fee recovery global and per form settings are outdated.

## Solution
Update the doc with the following screenshots
The Fee Recovery Global Settings Screen
![the fee recovery global settings screen](https://user-images.githubusercontent.com/3498917/51611097-68eb5080-1f44-11e9-9e8a-51de5cffbe1b.png)

The Fee Recovery Per Form Settings
![the fee recovery per form settings](https://user-images.githubusercontent.com/3498917/51611099-6ab51400-1f44-11e9-913c-17fbe7d5bf62.png)

## Acceptance Criteria

**This doc is ready to publish when:**
- [ ] I see updated screenshots for the Global and per form settings.

**Comment by mathetos** [comment]
Thanks @marutim I updated with your screenshots.
