### ISSUE TITLE
web-doc: add recurring donations for gocardless

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#214]
## Issue Info
* Docs URL: https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/recurring-donations-gocardless
* Doc Title: Recurring Donations with the GoCardless Gateway
* Issue Type: New

## Issue Description

We need to add this doc to the "Supported Payment Gateways" section of Recurring Donations. 

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] The doc is created with 
    - [x] an intro
    - [x] list of requirements
    - [x] a walkthrough
    - [x] relevant screenshots
    - [x] relevant links to related docs like Testing Mode, GoCardless docs, general Recurring docs
- [x] By the end of the article, users understand completely how to configure Give for recurring donations with GoCardless

**Comment by Benunc** [comment]
Started the doc here https://givewp.com/wp-admin/post.php?post=360551&action=edit

**Comment by Benunc** [comment]
published https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/gocardless/
