### ISSUE TITLE
web-doc: update permalink and featured image to correct spelling error

### ISSUE THREAD

**Issue by stephaniehellwig** [impress-org/give-docs#219]
## Issue Info
* Docs URL: https://givewp.com/documentation/developers/themeing-with-give/
* Doc Title: (only necessary if a new doc)
* Issue Type: Update

## Issue Description
All instances of themeing will need to be changed to theming.  

The featured image needs to be updated to reflect the correct (dictionary) spelling of the word theming.

The permalink needs to be corrected and a redirect implemented.

## Assets
<img width="291" alt="Screen Shot 2019-07-10 at 5 02 01 PM" src="https://user-images.githubusercontent.com/13453679/61005437-07b21080-a31d-11e9-8898-9684b21f2481.png">

## Related Give Core/Add-on issues
Permalinks + redirect for: 
https://givewp.com/documentation/developers/themeing-with-give/themeing-give-archive-page/

https://givewp.com/documentation/developers/themeing-with-give/themeing-the-single-give-page/

## Acceptance Criteria

**This doc is ready to publish when:**
- [x] I see the word theming spelled correctly in the featured image
- [x] I see the permalink reflect the correct spelling of theming
- [x] I see a redirect in place

**Comment by stephaniehellwig** [comment]
Requested FI correction 8/22/19

**Comment by stephaniehellwig** [comment]
@mathetos The permalink needs to be changed here.

**Comment by mathetos** [comment]
The THEM-ing is complete.
