### ISSUE TITLE
Shortcode parameters for [give_donor_wall] do not match online documentation.

### ISSUE THREAD

**Issue by IanDLacy** [impress-org/give-docs#229]
Using Version 2.5.4

Documentation URL:
https://givewp.com/documentation/core/shortcodes/give_donor_wall/

There are probably more of these (listed below) that are wrong, but these are the only ones I needed to use, and therefore the only ones I noticed.

Documentation --> Reality
form --> form_id
donor_avatar=show|hide --> show_avatar=true|false
donor_comment=show|hide --> show_comments=true|false

**Comment by mathetos** [comment]
CLosing in favor of #216
