### ISSUE TITLE
Doc needed for new Subscription REST API endpoint

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/give-docs#52]
@DevinWalker commented on [Thu Nov 19 2015](https://github.com/WordImpress/Give-Recurring-Donations/issues/51)

With Give Recurring there is a new REST API endpoint for querying subscription data. This should be highlighted in a doc. Probably not a very high priority for launch so I'm going to leave this off a milestone for now.

---

@DevinWalker commented on [Wed Aug 17 2016](https://github.com/WordImpress/Give-Recurring-Donations/issues/51#issuecomment-240547732)

Pending completion of: https://github.com/WordImpress/Give-Recurring-Donations/issues/5

**Comment by Benunc** [comment]
Added this to the doc here. closing (though I noticed some issues that I will also be creating)

https://givewp.com/documentation/developers/give-api-reference/
