### ISSUE TITLE
UPDATE: PayPal Payments Pro Recurring Docs

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-docs#57]
**URL:** 
https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/paypal-pro/

**PROBLEM:** 
- [ ] The screenshots are outdated which causes confusion for users who are on the newer accounts (manager.paypal.com)
- [ ] There needs to be specific instructions for each different account type, and mention that PayFlow requires that they upgrade their account and there's an added fee involved with that.

@DevinWalker can you review and list any other items that need to be updated on this doc? I got a few customers who pointed out these discrepancies and needed clarification because the Doc was basically unhelpful as-is.

**Comment by samsmith89** [comment]
This Doc is blocked by this issue:
https://github.com/WordImpress/Give-Recurring-Donations/issues/638

**Comment by mathetos** [comment]
@samsmith89 The linked issue is closed, so this doc should proceed now.

**Comment by samsmith89** [comment]
Link to the Google Doc:
https://docs.google.com/document/d/1wmIQ3E2IoRYlhk9lREQOvgLj3STcegzNmNmvXboCIb0/edit?usp=sharing

**Comment by samsmith89** [comment]
This is now live here:
https://givewp.com/documentation/add-ons/recurring-donations/supported-payment-gateways/paypal-pro/
Let me know if this is sufficient, and I will remove the section detailing the IPN URL and close this issue.

**Comment by samsmith89** [comment]
Changed the order of the Payflow instructions to the top, and left the IPN settings for legacy accounts. Closing
