### ISSUE TITLE
UPDATE: Add clarification for Form Field Manager field location options 

### ISSUE THREAD

**Issue by Benunc** [impress-org/give-docs#90]
**URL:** https://givewp.com/documentation/add-ons/form-field-manager/form-field-manager-101/

**PROBLEM:** There's no section outlining how the field placement options relate to the modal/button mode options, and how to get fields to show up on the modal.
 
**SOLUTION:** We need to add clarification there.

### Acceptance criteria
- [x] the screenshot are updated
- [x] the first person language is removed
- [x] the process for adding fields is updated
- [x] a line includes the fact that you have to add fields all in one place

**Comment by mathetos** [comment]
@Benunc please review this issue and provide new acceptance criteria. I see outdated screenshots and quite a few other items in desperate need of updating.

**Comment by Benunc** [comment]
Updated and done.

**Comment by mathetos** [comment]
Great work here, I just did a couple other minor tweaks.
